stages:
  - build
  - test

build:
  stage: build
  script:
    - python ./test_example.py

test:
  stage: test
  script:
    - python -m pytest test_example.py

test_app:
  stage: test
  script:
    - python ./app.py
