#Поддерживаемая версия
target-version = "py313"

#Основные настройки
#Максимальная длина строки в коде
line-length = 50 
#Ширина отступа
#indent-width = 

#Используемые правила линтра
[lint]
preview = true
select = [
"ERA",
"B",
"A",
"COM",
"C4",
"DTZ",
"DJ",
"EM",
"FIX",
"ISC",
"PIE",
"T20",
"PT",
"RSE",
"TD",
"E",
"W",
"PLE",
"FURB",
"RUF"
]
#Игнорирование конкретных правил линтера
#ignore = []
#Исключение папок файлов из проверки линтера
exclude = [
"apipy/**",
"build/**",
"builds/**",
"dist/**",
"__pycache__/**",
".git/**",
".idea/**",
".pytest_cache/**",
".ruff_cache/**"
]
#Ошибки которые можно исправить автоматически
fixable = [
"COM",
"RSE"]
#Настройка формата [format]
